version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - message_processor

  message_processor:
    build: ./message_processor
    ports:
      - "5001:5001"